In [ ]:
# Task1
import numpy as np

# Random integers from 0 to 100
random_int_array = np.random.randint(0, 100, size=10)

print(random_int_array)

[ 3 81 72 18 48 19 89 41 33 52]


In [ ]:
# Task2...
import numpy as np

# Creating a 2D array of size 7x6
original_array = np.arange(42).reshape(7, 6)

print("Original 2D Array (7x6):")
print(original_array)

# Reshaping the array to a 3x14 array
reshaped_array = original_array.reshape(3, 14)

print("\nReshaped 2D Array (3x14):")
print(reshaped_array)

Original 2D Array (7x6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]]

Reshaped 2D Array (3x14):
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36 37 38 39 40 41]]


In [ ]:
# Task3...
import numpy as np

original_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# calculate the mod
# If the number is not divisible by 2 we can add them to odd_numbers then print them
odd_numbers = original_array[original_array % 2 != 0]

print(odd_numbers)

[1 3 5 7 9]


In [ ]:
# Task4...
import numpy as np

original_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# If the number is not divisible by 2 we can replace the positions with -1
original_array[original_array % 2 != 0] =-1

print(original_array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [14]:
# Task5...
import numpy as np

original_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Created a temp list that prevents us from modifying the original_array
temp = np.where(original_array%2!=0,-1,original_array.copy())

print(temp)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [13]:
# Task6...
import numpy as np

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# where is a module of numpy that matches two corresponding postion value of the given lists and match them
# If the numbers are matched, the indices are saved in machine_position list
matching_positions = np.where(a == b)

print(matching_positions)


(array([1, 3, 5, 7]),)


In [17]:
# Task7...
import numpy as np

a = np.array([2, 6, 1, 9, 10, 3, 27])

# Filters the numbers that are greater than 5 and less than 10
filtered_items = a[(a >= 5) & (a <= 10)]

print(filtered_items)

[ 6  9 10]


In [27]:
# Task8...
import numpy as np

# Creating a vector of size 10 with zeros
zeros_vector = np.zeros(10)

# Creating a vector of size 10 with ones
ones_vector = np.ones(10)

# Changing their dimensions
zeros_matrix = zeros_vector[:, np.newaxis]
ones_matrix = ones_vector[:, np.newaxis]

# Merging vertically using concatenate
vertical_merged = np.concatenate((zeros_matrix, ones_matrix), axis=0)

# Merging horizontally using concatenate
horizontal_merged = np.concatenate((zeros_matrix, ones_matrix), axis=1)

print("Zeros Matrix:")
print(zeros_matrix)

print("\nOnes Matrix:")
print(ones_matrix)

print("\nVertically Merged Matrix:")
print(vertical_merged)

print("\nHorizontally Merged Matrix:")
print(horizontal_merged)


Zeros Matrix:
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

Ones Matrix:
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

Vertically Merged Matrix:
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

Horizontally Merged Matrix:
[[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [42]:
# Task9...
import numpy as np

# Created a matrix of size 5x4 with random numbers between 0 and 50
ndarray = np.random.randint(0,50,size = (5,4))

print(ndarray)


[[40 13  7 20]
 [ 0 42  2 18]
 [ 1 33 39 12]
 [39 10 28 10]
 [ 7 17 40  4]]


In [31]:
# Task10...
import numpy as np

#
x=np.random.rand(5,4)
y=np.random.randint(0,2,5)

print('x =', x)
print('y =', y)

x = [[0.48177963 0.68286688 0.70183391 0.52983859]
 [0.24355062 0.11336812 0.88641367 0.08306168]
 [0.49816192 0.74500784 0.09272058 0.00616618]
 [0.31381874 0.25968436 0.86284271 0.1183659 ]
 [0.88989034 0.28143115 0.62600586 0.01656519]]
y = [0 0 0 0 1]


In [33]:
# Task11...
def extract_subset(x,y,y0):
  return x[y == y0]

print(extract_subset(x,y,1))

[[0.88989034 0.28143115 0.62600586 0.01656519]]


In [48]:
# # Task12...
# import pandas as pd

# # Load the Iris dataset from scikit-learn
# from sklearn.datasets import load_iris
# iris = load_iris()

# # Create a DataFrame with both text and numeric components
# iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

# print(iris_df)

import numpy as np

# Load the IRIS dataset
url = "https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv"
data = np.genfromtxt(url, delimiter=',', skip_header=1, dtype=None, encoding=None)

print(data)



[(5.1, 3.5, 1.4, 0.2, 'setosa') (4.9, 3. , 1.4, 0.2, 'setosa')
 (4.7, 3.2, 1.3, 0.2, 'setosa') (4.6, 3.1, 1.5, 0.2, 'setosa')
 (5. , 3.6, 1.4, 0.2, 'setosa') (5.4, 3.9, 1.7, 0.4, 'setosa')
 (4.6, 3.4, 1.4, 0.3, 'setosa') (5. , 3.4, 1.5, 0.2, 'setosa')
 (4.4, 2.9, 1.4, 0.2, 'setosa') (4.9, 3.1, 1.5, 0.1, 'setosa')
 (5.4, 3.7, 1.5, 0.2, 'setosa') (4.8, 3.4, 1.6, 0.2, 'setosa')
 (4.8, 3. , 1.4, 0.1, 'setosa') (4.3, 3. , 1.1, 0.1, 'setosa')
 (5.8, 4. , 1.2, 0.2, 'setosa') (5.7, 4.4, 1.5, 0.4, 'setosa')
 (5.4, 3.9, 1.3, 0.4, 'setosa') (5.1, 3.5, 1.4, 0.3, 'setosa')
 (5.7, 3.8, 1.7, 0.3, 'setosa') (5.1, 3.8, 1.5, 0.3, 'setosa')
 (5.4, 3.4, 1.7, 0.2, 'setosa') (5.1, 3.7, 1.5, 0.4, 'setosa')
 (4.6, 3.6, 1. , 0.2, 'setosa') (5.1, 3.3, 1.7, 0.5, 'setosa')
 (4.8, 3.4, 1.9, 0.2, 'setosa') (5. , 3. , 1.6, 0.2, 'setosa')
 (5. , 3.4, 1.6, 0.4, 'setosa') (5.2, 3.5, 1.5, 0.2, 'setosa')
 (5.2, 3.4, 1.4, 0.2, 'setosa') (4.7, 3.2, 1.6, 0.2, 'setosa')
 (4.8, 3.1, 1.6, 0.2, 'setosa') (5.4, 3.4, 1.5, 0.4, 's

In [8]:
# Task13...
# import pandas as pd
# import numpy as np

# # Load the Iris dataset from scikit-learn
# from sklearn.datasets import load_iris
# iris = load_iris()

# # Create a DataFrame
# iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

# # Calculating statistics for the 1st column (sepal length)
# sepal_length = iris_df[iris.feature_names[0]]
# mean_sepal_length = np.mean(sepal_length)
# median_sepal_length = np.median(sepal_length)
# std_dev_sepal_length = np.std(sepal_length)

# # Display statistics for the 1st column
# print("Statistics for Sepal Length:")
# print("Mean:", mean_sepal_length)
# print("Median:", median_sepal_length)
# print("Standard Deviation:", std_dev_sepal_length)

# # Display statistical summary of the entire dataset
# print("\nStatistical Summary of the Dataset:")
# print(iris_df.describe())

import numpy as np

# Load the IRIS dataset
url = "https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv"
data = np.genfromtxt(url, delimiter=',', skip_header=1)

# Extract the first column
first_column = data[:, 0]

# Calculate mean, median, and standard deviation
mean = np.mean(first_column)
median = np.median(first_column)
std_dev = np.std(first_column)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

print(data)

Mean: 5.843333333333334
Median: 5.8
Standard Deviation: 0.8253012917851409
[[5.1 3.5 1.4 0.2 nan]
 [4.9 3.  1.4 0.2 nan]
 [4.7 3.2 1.3 0.2 nan]
 [4.6 3.1 1.5 0.2 nan]
 [5.  3.6 1.4 0.2 nan]
 [5.4 3.9 1.7 0.4 nan]
 [4.6 3.4 1.4 0.3 nan]
 [5.  3.4 1.5 0.2 nan]
 [4.4 2.9 1.4 0.2 nan]
 [4.9 3.1 1.5 0.1 nan]
 [5.4 3.7 1.5 0.2 nan]
 [4.8 3.4 1.6 0.2 nan]
 [4.8 3.  1.4 0.1 nan]
 [4.3 3.  1.1 0.1 nan]
 [5.8 4.  1.2 0.2 nan]
 [5.7 4.4 1.5 0.4 nan]
 [5.4 3.9 1.3 0.4 nan]
 [5.1 3.5 1.4 0.3 nan]
 [5.7 3.8 1.7 0.3 nan]
 [5.1 3.8 1.5 0.3 nan]
 [5.4 3.4 1.7 0.2 nan]
 [5.1 3.7 1.5 0.4 nan]
 [4.6 3.6 1.  0.2 nan]
 [5.1 3.3 1.7 0.5 nan]
 [4.8 3.4 1.9 0.2 nan]
 [5.  3.  1.6 0.2 nan]
 [5.  3.4 1.6 0.4 nan]
 [5.2 3.5 1.5 0.2 nan]
 [5.2 3.4 1.4 0.2 nan]
 [4.7 3.2 1.6 0.2 nan]
 [4.8 3.1 1.6 0.2 nan]
 [5.4 3.4 1.5 0.4 nan]
 [5.2 4.1 1.5 0.1 nan]
 [5.5 4.2 1.4 0.2 nan]
 [4.9 3.1 1.5 0.1 nan]
 [5.  3.2 1.2 0.2 nan]
 [5.5 3.5 1.3 0.2 nan]
 [4.9 3.1 1.5 0.1 nan]
 [4.4 3.  1.3 0.2 nan]
 [5.1 3.4 1.5 0.2 nan]
 [5. 